### ISSUE TITLE
ixgbe_validate_register_read: register ee2c read recovered after 1 retries

### ISSUE THREAD

**Issue by 0xFelix** [majek/ixgbe#1]
What does this error message mean or what does it mean when the driver reaches line 388 in  'ixgbe/src/ixgbe_main.c' ?

Our server reboots from time to time and there is absolutely no indication for what is wrong.

This is the only line in the kernel log that seems to be suspicious.

**Comment by dip3323d** [comment]
I'm getting the same message:
ixgbe_validate_register_read: register ee2c read recovered after 1 retries
and I can correlate lost of packets with it
Messages started since 30th of October 2015

**Comment by dip3323d** [comment]
We've got answer from network card manufacture, that it could be error in driver.
